server {
  host = "0.0.0.0"
  host = ${?HOST}
  port = 8080
  port = ${?PORT}
}

nws-client {
  timeout-seconds = 10
  timeout-seconds = ${?CLIENT_TIMEOUT_SECONDS}
  max-retries = 3
  max-retries = ${?MAX_RETRIES}
}

cache {
  ttl-minutes = 30
  ttl-minutes = ${?CACHE_TTL_MINUTES}
}
